version: "3.8"
services:
  libretranslate:
    container_name: LibreTranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    environment:
      - LT_LOAD_ONLY=en,bg # Languages, from-to which you want to support translation. Keep it minimal to save resources.
      - LT_DISABLE_WEB_UI=false # Optional, enable if you would like to make use of the LibreTranslate web interface
    network_mode: host
    volumes:
      # - ../data/libretranslate:/home/libretranslate/.local/share/argos-translate
      - libretranslate_models:/home/libretranslate/.local:rw
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]

volumes:
   libretranslate_models:
