version: "3.8"
services:
  libretranslate:
    container_name: LibreTranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    environment:
      - LT_LOAD_ONLY=en,bg # Languages, from-to which you want to support translation. Keep it minimal to save resources.
      - LT_DISABLE_WEB_UI=false # Optional, enable if you would like to make use of the LibreTranslate web interface
    ports:
      - "5000:5000"
    volumes:
      # - ../data/libretranslate:/home/libretranslate/.local/share/argos-translate
      - libretranslate_models:/home/libretranslate/.local:rw
    networks:
      - libretranslate
    healthcheck:
      test: ["CMD-SHELL", "./venv/bin/python scripts/healthcheck.py"]

  api-translate:
    container_name: api-translate
    build: ./api-translate
    restart: unless-stopped
    environment:
      - LIBRETRANSLATE_URL=http://LibreTranslate:5000
      - TARGET_LANGUAGE=${TARGET_LANGUAGE}  # Използване на променливата от .env файла
      - RESULT_FOLDER=${RESULT_FOLDER}
      - SRT_FILES_PATH=${SRT_FILES_PATH}
    networks:
      - libretranslate
    depends_on:
      libretranslate:
        condition: service_healthy
    # stdin_open: true
    # tty: true
    entrypoint: ["python", "translate_srt.py"]  # Стандартният скрипт
    command: ["translate_srt.py"]  # Това може да се променя при стартиране
    volumes:
      - ${SRT_FILES_PATH}:/app/data  # Използваме променливата от .env файла

networks:
  libretranslate:
    driver: bridge
volumes:
   libretranslate_models:
